# Generated by Django 5.2.7 on 2025-10-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
