# Generated by Django 5.2.7 on 2025-10-19 10:18

import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File_Up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('file_id', models.CharField(default=uploads.models.generate_uuid, editable=False, max_length=36, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
