# Generated by Django 5.2.7 on 2025-11-29 10:50

import django.db.models.deletion
import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(default=uploads.models.generate_file_id, max_length=100, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100, null=True)),
                ('size', models.BigIntegerField(null=True)),
                ('ciphertext', models.TextField(null=True)),
                ('iv', models.CharField(max_length=255, null=True)),
                ('salt', models.CharField(max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='user.users')),
            ],
        ),
    ]
