# Generated by Django 5.2.7 on 2025-11-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='title',
            new_name='original_name',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='file',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='ciphertext',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='iv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='mime_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='salt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='size',
            field=models.BigIntegerField(null=True),
        ),
    ]
