# Generated by Django 5.2.7 on 2025-10-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_up',
            name='id',
        ),
        migrations.AddField(
            model_name='file_up',
            name='file_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
