# Generated by Django 5.2.7 on 2026-03-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_fileupload_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='analysis_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file_extension',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='is_safe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='last_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
    ]
