# Generated by Django 5.2.7 on 2025-10-19 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_alter_file_up_owner'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_up',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='user.users'),
        ),
    ]
