# Generated by Django 5.2.7 on 2026-01-10 06:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boardOrganisation', '0003_alter_memberdetailmodel_memberinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.CharField(db_index=True, max_length=64)),
                ('user_id', models.IntegerField()),
                ('op_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('version', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['board_id', 'version'], name='board_board_board_i_b310c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='BoardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.CharField(db_index=True, max_length=64)),
                ('layers', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.BigIntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['board_id', 'version'], name='board_board_board_i_79d267_idx')],
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authorId', models.CharField(max_length=50)),
                ('authorName', models.CharField(max_length=100)),
                ('fav', models.BooleanField(default=False, null=True)),
                ('imageUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('boardId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='boardOrganisation.organisationmodel')),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='title_search_idx')],
            },
        ),
    ]
