# Generated by Django 5.2.7 on 2025-12-01 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boardOrganisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authorId', models.CharField(max_length=50)),
                ('authorName', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='boardOrganisation.organisationmodel')),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='title_search_idx')],
            },
        ),
    ]
