# Generated by Django 5.2.7 on 2025-12-02 11:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='boardId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
