# Generated by Django 5.2.7 on 2025-12-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_boardid'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='fav',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
