# Generated by Django 5.2.7 on 2025-11-29 10:50

import boardOrganisation.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisationName', models.CharField(max_length=150)),
                ('organisationId', models.CharField(default=boardOrganisation.models.generate_file_id, max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('role', models.CharField(default='admin', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('imgUrl', models.ImageField(blank=True, null=True, upload_to='organisation_logos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
        migrations.CreateModel(
            name='memberDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(max_length=40)),
                ('role', models.CharField(default='member', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('memberInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.users')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardOrganisation.organisationmodel')),
            ],
        ),
    ]
