# Generated by Django 5.2.7 on 2025-11-30 11:07

import boardOrganisation.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisationName', models.CharField(max_length=150)),
                ('organisationId', models.CharField(default=boardOrganisation.models.generate_file_id, max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('imgUrl', models.ImageField(blank=True, null=True, upload_to='organisation_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='memberDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(max_length=40)),
                ('role', models.CharField(default='member', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('memberInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.users')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardOrganisation.organisationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(default='member', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardOrganisation.organisationmodel')),
            ],
        ),
    ]
