# Generated by Django 5.2.7 on 2025-12-21 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardOrganisation', '0002_alter_organisationmodel_creator'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdetailmodel',
            name='memberInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_memberships', to='user.users'),
        ),
    ]
