# Generated by Django 5.2.7 on 2026-03-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_alter_workspace_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='repo',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='type',
            field=models.CharField(default='local'),
        ),
    ]
